GET http://localhost:8080/patienten
Content-Type: application/json

###

PATCH http://localhost:8080/profile/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "praxisName": "Sample Praxis",
  "inhaberName": "John Doe",
  "profilePictureUrl": "https://example.com/profile.jpg"
}

###

GET http://localhost:8080/profile/d7e8f9a0-b1c2-3d4e-5f6a-7b8c9d0e1f2a/kalender?
    accessToken=5a6b7c8d-9e0f-1a2b-3c4d-5e6f7a8b9c0d
Content-Type: application/json


###

GET http://localhost:8080/behandlungen
Content-Type: application/json


###

GET http://localhost:8080/behandlungen/calender/week?date=2024-04-02
Content-Type: application/json

###

POST http://localhost:8080/patienten
Content-Type: application/json

{
  "titel": null,
  "vorname": "Torben",
  "nachname": "Keller",
  "strasse": "Brunswiker Str.",
  "hausnummer": "35",
  "plz": "24103",
  "stadt": "Kiel",
  "telMobil": "+49 177 6320739",
  "telFestnetz": "",
  "email": "torben2012@live.de",
  "geburtstag": "1999-09-15"
}

####
PUT http://localhost:8080/behandlungen/11a2b3c4-d5e6-7f8a-9b0c-1d2e3f4a5b6c/verschiebe
Content-Type: application/json

{
  "nach": "2025-06-04T10:00:00"
}