// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser, formDataBodySerializer } from '@hey-api/client-fetch';
import type { CreateFromImageData, CreateFromImageError, CreateFromImageResponse, GetPatientenError, GetPatientenResponse, CreatePatientData, CreatePatientError, CreatePatientResponse, DeletePatientData, DeletePatientError, DeletePatientResponse, UpdatePatientData, UpdatePatientError, UpdatePatientResponse, GetRezepteError, GetRezepteResponse, ServeFileData, ServeFileError, ServeFileResponse, DeleteRezeptData, DeleteRezeptError, DeleteRezeptResponse } from './types.gen';

export const client = createClient(createConfig());

export const createFromImage = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<CreateFromImageData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateFromImageResponse, CreateFromImageError, ThrowOnError>({
        ...options,
        ...formDataBodySerializer,
        headers: {
            'Content-Type': null,
            ...options?.headers
        },
        url: '/rezepte/createFromImage'
    });
};

export const getPatienten = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPatientenResponse, GetPatientenError, ThrowOnError>({
        ...options,
        url: '/patienten'
    });
};

export const createPatient = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreatePatientData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreatePatientResponse, CreatePatientError, ThrowOnError>({
        ...options,
        url: '/patienten'
    });
};

export const deletePatient = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeletePatientData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeletePatientResponse, DeletePatientError, ThrowOnError>({
        ...options,
        url: '/patienten/{id}'
    });
};

export const updatePatient = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UpdatePatientData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UpdatePatientResponse, UpdatePatientError, ThrowOnError>({
        ...options,
        url: '/patienten/{id}'
    });
};

export const getRezepte = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetRezepteResponse, GetRezepteError, ThrowOnError>({
        ...options,
        url: '/rezepte'
    });
};

export const serveFile = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ServeFileData, ThrowOnError>) => {
    return (options?.client ?? client).get<ServeFileResponse, ServeFileError, ThrowOnError>({
        ...options,
        url: '/rezepte/rezepte/tmp/{filename}'
    });
};

export const deleteRezept = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteRezeptData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteRezeptResponse, DeleteRezeptError, ThrowOnError>({
        ...options,
        url: '/rezepte/{id}'
    });
};